name: lge_mri_qc_multiclass
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.1=h7b32b05_0
  - pip=25.0.1=pyh8b19718_0
  - python=3.12.9=h9e4cc4f_1_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=75.8.2=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - attrs==25.3.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - comet-ml==3.49.5
      - configobj==5.0.9
      - contourpy==1.3.1
      - cycler==0.12.1
      - dulwich==0.22.8
      - everett==3.1.0
      - filelock==3.18.0
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - idna==3.10
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lightning-utilities==0.14.2
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - monai==1.4.0
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - psutil==7.0.0
      - pygments==2.19.1
      - pynrrd==1.1.3
      - pyparsing==3.2.1
      - python-box==6.1.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - referencing==0.36.2
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rpds-py==0.23.1
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentry-sdk==2.23.1
      - simplejson==3.20.1
      - six==1.17.0
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - torch==2.6.0
      - torchmetrics==1.6.3
      - torchvision==0.21.0
      - tqdm==4.67.1
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - urllib3==2.3.0
      - wrapt==1.17.2
      - wurlitzer==3.1.1
      - ruff==0.11.2
      - mypy==1.15.0
      - pre-commit==4.2.0
      - python-dotenv==1.1.0
      